### ISSUE TITLE
Errore 400 da Telegram

### ISSUE THREAD

**Issue by valeriogalano** [valeriogalano/pensieriincodice-news-to-telegram#1]
La chiamata ritorna va 400 quando tenta di inviare il messaggio Telegram.

Log disponibile presso https://github.com/valeriogalano/pensieriincodice-news-to-telegram/actions/runs/9001561646/job/24728052017

**Comment by progressify** [comment]
Credo che questa si possa chiudere 🤔
Ho gestito con un'eccezione l'errore

https://github.com/valeriogalano/pensieriincodice-news-to-telegram/blob/14d017afedb20d2f1aa69c4e5801a469e0f7e173/telegram_helper.py#L48

**Comment by valeriogalano** [comment]
Grazie.
