### ISSUE TITLE
Quotare caratteri riservati

### ISSUE THREAD

**Issue by valeriogalano** [valeriogalano/pensieriincodice-news-to-telegram#5]
Nei placeholder _title_ e _notes_ vanno quotati i seguenti caratteri:
'_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!'

**Comment by progressify** [comment]
Ho ottimizzato il codice, al prossimo giro controlliamo se è tutto ok e poi chiudo la issue :)

**Comment by valeriogalano** [comment]
Funziona perfettamente. Grazie.
